[package]
name        = "travelling_salesman"
version     = "0.0.7"
authors     = ["Alfie John <alfie@alfie.wtf>"]

description   = "Travelling Salesman Problem Solvers"
homepage      = "https://crates.io/crates/travelling_salesman"
repository    = "https://github.com/alfiedotwtf/travelling_salesman"

license = "GPL-3.0"

[dependencies]
rand           = "0.3.10"
time           = "0.1.30"
metaheuristics = "0.0.4"
