[package]
name        = "travelling_salesman"
version     = "0.0.9"
authors     = ["Alfie John <alfie@alfie.wtf>"]

description   = "Travelling Salesman Problem Solvers"
documentation = "https://www.alfie.wtf/rustdoc/travelling_salesman/travelling_salesman/"
homepage      = "https://crates.io/crates/travelling_salesman"
repository    = "https://github.com/alfiedotwtf/travelling_salesman"

license = "GPL-3.0"

[dependencies]
metaheuristics = "0.0.6"
rand           = "0.3.10"
time           = "0.1.30"
